CREATE TABLE PROFIL(ID int AUTO_INCREMENT NOT NULL PRIMARY KEY, NOM varchar(50), MDP varchar(100) NOT NULL, EMAIL varchar(50) NOT NULL UNIQUE, EXPIRATION date, DTYPE varchar(31));
CREATE TABLE GROUPES(ID int AUTO_INCREMENT NOT NULL PRIMARY KEY, NOM varchar(50) NOT NULL UNIQUE, DESCRIPTION varchar(300));
CREATE TABLE PROFIL_GROUPES(NOM varchar(50) NOT NULL, EMAIL varchar(50) NOT NULL);
ALTER TABLE PROFIL_GROUPES ADD CONSTRAINT FK_PROFIL_GROUPES_PROFIL FOREIGN KEY (EMAIL) REFERENCES PROFIL(EMAIL);
ALTER TABLE PROFIL_GROUPES ADD CONSTRAINT FK_PROFIL_GROUPES_GROUPES FOREIGN KEY (NOM) REFERENCES GROUPES(NOM);
CREATE INDEX SQL_PROFILGROUPES_EMAIL_INDEX ON PROFIL_GROUPES(EMAIL);
CREATE INDEX SQL_PROFILGROUPES_ID_INDEX ON PROFIL_GROUPES(NOM);

CREATE TABLE ENTREPRISE(ID int AUTO_INCREMENT NOT NULL PRIMARY KEY, RAISON_SOCIALE varchar(50) NOT NULL, FORME_JURIDIQUE varchar(50), NATURE varchar(20), SIRET varchar(20), NUMERO_TVA varchar(20), ENTREPRISE_ID int, PROFIL_ID int);
CREATE TABLE PERSONNE(ID int AUTO_INCREMENT NOT NULL PRIMARY KEY, CIVILITE varchar(5) NOT NULL, NOM varchar(50) NOT NULL, PRENOM varchar(100) NOT NULL, COORDONNEES_ID int, ENTREPRISE_ID int);
CREATE UNIQUE INDEX SQL_PERSONNE_EMAIL_INDEX ON PROFIL(EMAIL);
CREATE UNIQUE INDEX SQL_PERSONNE_ID_INDEX ON PROFIL(ID);
CREATE TABLE COORDONNEES(ID int AUTO_INCREMENT NOT NULL PRIMARY KEY, RUE varchar(50) NOT NULL, CODE_POSTAL varchar(6) NOT NULL, VILLE varchar(50) NOT NULL, PAYS varchar(50), EMAIL varchar(50), TEL varchar(20), FAX varchar(20), ENTREPRISE_ID int);
ALTER TABLE ENTREPRISE ADD CONSTRAINT FK_ENTREPRISE_PROFIL FOREIGN KEY (PROFIL_ID) REFERENCES PROFIL(ID);
ALTER TABLE ENTREPRISE ADD CONSTRAINT FK_ENTREPRISE_ENTREPRISE FOREIGN KEY (ENTREPRISE_ID) REFERENCES ENTREPRISE(ID);
ALTER TABLE PERSONNE ADD CONSTRAINT FK_PERSONNE_ENTREPRISE FOREIGN KEY (ENTREPRISE_ID) REFERENCES ENTREPRISE(ID);
ALTER TABLE PERSONNE ADD CONSTRAINT FK_PERSONNE_COORDONNEES FOREIGN KEY (COORDONNEES_ID) REFERENCES COORDONNEES(ID);
ALTER TABLE COORDONNEES ADD CONSTRAINT FK_COORDONNEES_ENTREPRISE FOREIGN KEY (ENTREPRISE_ID) REFERENCES ENTREPRISE(ID);
