ALTER TABLE PROFIL_GROUPES DROP FOREIGN KEY FK_PROFIL_GROUPES_PROFIL;
ALTER TABLE PROFIL_GROUPES DROP FOREIGN KEY FK_PROFIL_GROUPES_GROUPES;
ALTER TABLE ENTREPRISE DROP FOREIGN KEY FK_ENTREPRISE_PROFIL;
ALTER TABLE ENTREPRISE DROP FOREIGN KEY FK_ENTREPRISE_ENTREPRISE;
ALTER TABLE PERSONNE DROP FOREIGN KEY FK_PERSONNE_ENTREPRISE;
ALTER TABLE PERSONNE DROP FOREIGN KEY FK_PERSONNE_COORDONNEES;
ALTER TABLE COORDONNEES DROP FOREIGN KEY FK_COORDONNEES_ENTREPRISE;

DROP TABLE PROFIL_GROUPES;
DROP TABLE PROFIL;
DROP TABLE GROUPES;
DROP TABLE ENTREPRISE;
DROP TABLE PERSONNE;
DROP TABLE COORDONNEES;